# Generated by Django 3.0.5 on 2020-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_slug',
            field=models.SlugField(blank=True, default='', null=True, verbose_name='Порода животного для URL'),
        ),
    ]
