# Generated by Django 3.0.5 on 2020-04-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200430_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_slug',
            field=models.SlugField(blank=True, default=None, null=True, verbose_name='Порода животного для URL'),
        ),
    ]
